version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP server port
      - "8025:8025"  # Web UI port
    networks:
      - mail_net

  app:
    build: .
    depends_on:
      - mailhog
    environment:
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USER=
      - SMTP_PASSWORD=
    networks:
      - mail_net
    volumes:
      - ./templates:/app/templates  # Mount templates directory
    restart: unless-stopped

networks:
  mail_net:
    driver: bridge
